# Generated by Django 3.1.2 on 2023-04-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zentao_id', models.IntegerField(blank=True, null=True, verbose_name='禅道ID')),
                ('name', models.CharField(max_length=100, verbose_name='需求名称')),
                ('url', models.CharField(max_length=200, verbose_name='需求链接')),
                ('proposer', models.CharField(max_length=10, verbose_name='提出方')),
                ('pm', models.CharField(max_length=10, verbose_name='产品经理')),
                ('version', models.CharField(blank=True, max_length=20, null=True, verbose_name='版本')),
                ('status', models.IntegerField(choices=[(0, '未启动'), (1, '需求沟通中'), (2, '进行中'), (3, '验收完成'), (4, '已撤销')], default=0, verbose_name='需求状态')),
                ('review_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='需求评审时间')),
                ('description', models.CharField(max_length=300, verbose_name='备注')),
                ('categray', models.IntegerField(choices=[(0, '运营需求'), (1, '外部需求'), (2, '自发需求')], verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '需求池',
                'permissions': (['edit_need', '编辑需求内容'],),
            },
        ),
        migrations.CreateModel(
            name='NeedsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '需求分类',
            },
        ),
    ]
